### ISSUE TITLE
Erro: (node:5070) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by joaoP-santos** [rocketseat-content/youtube-codedrops-adminbro#1]
Já tentei de tudo, cheguei a clonar o repositório e tentar ligar o servidor sem mexer em nada, mas não adianta: sempre retorna esse erro. Não encontrei material sobre o assunto e não sei se é um erro causado pelo código ou pela aplicação em si, mas peço que me ajudem pois me empolguei muito com essa biblioteca.

**Comment by jpedroschmitz** [comment]
Você tem o MongoDB rodando na sua máquina? Isso é erro de conexão

**Comment by joaoP-santos** [comment]
> Você tem o MongoDB rodando na sua máquina? Isso é erro de conexão

Não. É que no vídeo não foi deixado claro que precisava do MongoDB rodando ou talvez eu não percebi. Sou iniciante e ainda não aprendi a mexer com Mongo, mas vou ver o que posso fazer para rodar e testar. De qualquer forma, obrigado pelo retorno. :smile:

**Comment by joaoP-santos** [comment]
Bom dia. Consegui realizar a conexão com a db e funciona certinho agora. Valeu! :+1:
